#############################################################################
#
# makefile.link
#
# common settings for a native project
#
# (c) Wouter van Ooijen (www.voti.nl) 2017
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at 
# http://www.boost.org/LICENSE_1_0.txt)
# 
#############################################################################

# common settings
TARGET            ?= native

# get the paths 
RELATIVE          ?= ..
HWLIB             := $(RELATIVE)/makefile.link
